# Generated by Django 4.2.5 on 2023-10-04 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название урока')),
                ('video', models.URLField(max_length=250, verbose_name='URL видео')),
                ('duration_video', models.IntegerField(verbose_name='Длительность видео в секундах')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ к уроку')),
                ('watched_video', models.IntegerField(verbose_name='Просмотренное видео в секундах')),
                ('status', models.CharField(choices=[('Просмотрено', 'Просмотрено'), ('Не просмотрено', 'Не просмотрено')], default='Не просмотрено', max_length=14, verbose_name='Статус просмотра')),
                ('view_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
